on: [pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: peruseRN

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          cache: npm

      - name: 📦 Install dependencies
        run: yarn --frozen-lockfile

      - nam: Check vulnerabilities
        run: yarn run audit

      - name: Run lint
        run: yarn run lint

      - name: Run tests
        run: yarn run test

      - name: 🚀 Publish preview
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: 💬 Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          channel: pr-${{ github.event.number }}
